name: space_farers

dependencies:
- geopandas
- fiona
- folium 
- os
- geemap
- ee
- sklearn
- sklearn.ensemble
- sklearn.model_selection
- unittest
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- statsmodels
- jmcmurray os
- calplot
- pip
- pip:
  - calplot
  - openpyxl
  
- conda
- conda:
  - jupyterlab
  - mamba


