name: space_farers

dependencies:
#- geopandas
#- fiona
#- folium 
#- os
#- geemap
#- ee
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn
#- scipy
#- statsmodels
#- os
#- datetime
#- openpyxl
#- statsmodels
#- geopandas
#- sklearn
- shapely
#- folium
#- pmdarima
- pydot

- pip
- pip:
  - scikit-learn
  #- unittest
  - calplot
  - openpyxl
  #- sklearn
  

  
  


