name: space_farers
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.8
#- geopandas
#- fiona
#- geemap
#- ee
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn 
- scipy
- statsmodels
#- os
#- datetime
#- geopandas
- shapely
- folium
- pmdarima
- pydot
- conda-forge::geopandas

- pip  
- pip:  
  - scikit-learn 
  #- unittest
  - calplot
  - openpyxl
  #- sklearn
  #- geopandas
  

  
  


