name: space_farers

dependencies:
- geopandas
- fiona
#- folium 
#- os
#- geemap
#- ee
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- statsmodels
- pip
- pip:
  - sklearn
  - unittest
  - sklearn.ensemble
  - sklearn.model_selection
  - calplot
  - openpyxl
  

  
  


